export const CATEGORIES_FETCH_ALL = 'CATEGORIES::FETCH_ALL'
export const CATEGORIES_SET_ALL = 'CATEGORIES::SET_ALL'

export const POSTS_ALL_BY_CATEGORY = 'POSTS::ALL_POSTS_BY_CATEGORY'
export const POSTS_ALL = 'POSTS::ALL_POSTS'
export const POSTS_SET_POSTS = 'POSTS::SET_POSTS'
export const POSTS_ORDER_BY = 'POSTS::ORDER_BY'
export const POSTS_UP_VOTE = 'POSTS::UP_VOTE'
export const POSTS_DOWN_VOTE = 'POSTS::DOWN_VOTE'
export const POSTS_UPDATE_POST_LIST = 'POSTS::UPDATE_POST_LIST'
export const SET_POST_SELECTED = 'POST::SET_POST_SELECTED'
export const LOAD_POST_SELECTED = 'POST::LOAD_POST_SELECTED'

export const TYPE_OF_ORDER_CHANGE = 'TYPE_OF_ORDER::CHANGE_ORDER'

export const COMMENTS_GET_ALL_BY_POST = 'COMMMENTS::GET_ALL_BY_POST'
export const COMMENTS_SET_COMMENTS = 'COMMENTS::SET_COMMENTS'